name: "Build and cache nix packages"
on:
  push: 
    branches: [ main ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --command bash -c "pnpm i && pnpm t && pnpm -F @holochain-open-dev/tasks build"

      - name: Build zomes
        env:
          CACHIX_AUTH_TOKEN: "$"
        run: |
          nix build -L .#tasks_integrity
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#tasks_integrity)
          cachix pin holochain-open-dev tasks_integrity_debug $(nix path-info --accept-flake-config .#tasks_integrity)

          nix build -L .#tasks_integrity.meta.release
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#tasks_integrity)
          cachix pin holochain-open-dev tasks_integrity $(nix path-info --accept-flake-config .#tasks_integrity.meta.release)

          nix build -L .#tasks
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#tasks)
          cachix pin holochain-open-dev tasks_debug $(nix path-info --accept-flake-config .#tasks)

          nix build -L .#tasks.meta.release
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#tasks.meta.release)
          cachix pin holochain-open-dev tasks $(nix path-info --accept-flake-config .#tasks.meta.release)
